<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use App\Models\ChecklistModels\Bulanan\JenisPengecekan;

class JenisPengecekanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        JenisPengecekan::insert([
            ["deskripsi" => "Kemanan"],
            ["deskripsi" => "Longgar"],
            ["deskripsi" => "Aus"],
            ["deskripsi" => "Cek Fungsi"],
            ["deskripsi" => "Pudar"],
            ["deskripsi" => "Kesesuaian"],
            ["deskripsi" => "Retak"],
            ["deskripsi" => "Bocor"],
            ["deskripsi" => "Serat"],
            ["deskripsi" => "Karat"],
            ["deskripsi" => "Getaran"],
            ["deskripsi" => "Suara"],
        ]);
        DB::table('bulanan_poin_jenis_pengecekan')->insert([
            ["bulanan_poin_id" => 1, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 1, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 2, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 2, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 3, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 3, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 4, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 4, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 4, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 5, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 6, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 7, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 8, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 9, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 10, "bulanan_pengecekan_id" => 5],
            ["bulanan_poin_id" => 10, "bulanan_pengecekan_id" => 6],
            ["bulanan_poin_id" => 11, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 11, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 12, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 13, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 13, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 14, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 14, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 15, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 15, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 16, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 16, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 17, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 17, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 17, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 18, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 18, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 19, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 19, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 20, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 20, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 20, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 21, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 22, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 22, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 22, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 23, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 23, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 23, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 24, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 25, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 26, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 27, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 28, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 29, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 30, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 30, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 30, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 31, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 31, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 32, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 32, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 32, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 33, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 33, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 34, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 34, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 34, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 35, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 36, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 36, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 37, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 37, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 37, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 37, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 38, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 38, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 38, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 39, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 39, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 39, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 40, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 40, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 40, "bulanan_pengecekan_id" => 9],
            ["bulanan_poin_id" => 41, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 41, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 41, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 42, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 42, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 42, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 43, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 43, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 43, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 44, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 44, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 44, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 45, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 46, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 46, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 46, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 47, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 47, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 47, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 48, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 48, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 48, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 49, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 49, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 49, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 50, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 50, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 51, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 51, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 51, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 51, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 52, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 52, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 53, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 53, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 53, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 54, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 54, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 55, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 55, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 55, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 56, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 57, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 58, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 58, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 59, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 59, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 60, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 61, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 61, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 61, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 62, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 62, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 62, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 63, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 63, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 64, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 64, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 64, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 65, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 65, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 65, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 66, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 66, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 66, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 67, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 67, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 67, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 68, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 68, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 68, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 68, "bulanan_pengecekan_id" => 7],
            ["bulanan_poin_id" => 69, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 69, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 69, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 70, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 70, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 71, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 71, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 72, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 72, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 72, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 73, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 73, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 74, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 74, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 75, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 75, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 76, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 76, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 76, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 77, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 77, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 78, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 78, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 78, "bulanan_pengecekan_id" => 10],
            ["bulanan_poin_id" => 79, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 79, "bulanan_pengecekan_id" => 3],
            ["bulanan_poin_id" => 80, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 80, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 81, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 81, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 81, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 82, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 82, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 82, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 83, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 83, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 83, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 84, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 84, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 85, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 85, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 85, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 86, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 86, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 86, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 87, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 87, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 87, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 88, "bulanan_pengecekan_id" => 1],
            ["bulanan_poin_id" => 88, "bulanan_pengecekan_id" => 2],
            ["bulanan_poin_id" => 88, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 89, "bulanan_pengecekan_id" => 4],
            ["bulanan_poin_id" => 90, "bulanan_pengecekan_id" => 8],
            ["bulanan_poin_id" => 90, "bulanan_pengecekan_id" => 11],
            ["bulanan_poin_id" => 90, "bulanan_pengecekan_id" => 12],
        ]);
    }
}
