<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\ChecklistModels\Harian\Poin as HarianPoin;
use App\Models\ChecklistModels\Mingguan\Poin as MingguanPoin;
use App\Models\ChecklistModels\Bulanan\Poin as BulananPoin;

class PoinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        HarianPoin::insert([
            ["deskripsi" => "Kondisi Rem", "harian_kategori_id" => 1],
            ["deskripsi" => "Kondisi Ban", "harian_kategori_id" => 1],
            ["deskripsi" => "Kondisi Wiper", "harian_kategori_id" => 1],
            ["deskripsi" => "Kondisi Lampu-lampu", "harian_kategori_id" => 1],
            ["deskripsi" => "Kondisi Kompartemen Tangki", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan APAR", "harian_kategori_id" => 1],
            ["deskripsi" => "Oli Mesin", "harian_kategori_id" => 1],
            ["deskripsi" => "Air Radiator", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan STNK", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Surat Keur", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Surat Tera", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Kotak P3K", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Flame Trap", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Ban Serep", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Tools Kit termasuk dongkrak", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Selang Bongkar", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Grounding Cable", "harian_kategori_id" => 1],
            ["deskripsi" => "Keberadaan Spill Kit", "harian_kategori_id" => 1],
            ["deskripsi" => "Membawa SIM sesuai jenis kendaraan", "harian_kategori_id" => 2],
            ["deskripsi" => "Surat Ijin Masuk Area TBBM Masih Berlaku", "harian_kategori_id" => 2],
            ["deskripsi" => "Menggunakan Seragam Kerja", "harian_kategori_id" => 2],
            ["deskripsi" => "Menggunakan Safety Shoes", "harian_kategori_id" => 2],
            ["deskripsi" => "Menggunakan Safety Helm", "harian_kategori_id" => 2],
            ["deskripsi" => "Menggunakan ID Card", "harian_kategori_id" => 2],
            ["deskripsi" => "Menggunakan Safety Glove (sarung tangan)", "harian_kategori_id" => 2],
            ["deskripsi" => "Membawa Jas Hujan", "harian_kategori_id" => 2],
            ["deskripsi" => "Membawa Buku Saku Service Excellence AMT", "harian_kategori_id" => 2],
            ["deskripsi" => "Membawa Catatan Perjalan AMT", "harian_kategori_id" => 2],
            ["deskripsi" => "Angka Awal", "harian_kategori_id" => 3],
            ["deskripsi" => "Angka Akhir", "harian_kategori_id" => 3],
        ]);
        MingguanPoin::insert([
            ["deskripsi" => "Head truck sumbu I", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Head truck sumbu II", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Head truck sumbu III", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Tangki trailer I", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Tangki trailer II", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Tangki trailer III", "is_krusial" => 0, "mingguan_sub_kategori_id" => 1],
            ["deskripsi" => "Head truck sumbu I", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Head truck sumbu II", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Head truck sumbu III", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Tangki trailer I", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Tangki trailer II", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Tangki trailer III", "is_krusial" => 0, "mingguan_sub_kategori_id" => 2],
            ["deskripsi" => "Berfungsi jauh", "is_krusial" => 0, "mingguan_sub_kategori_id" => 3],
            ["deskripsi" => "Berfungsi dekat", "is_krusial" => 0, "mingguan_sub_kategori_id" => 3],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 3],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 4],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 4],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 5],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 5],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 6],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 6],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 7],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 7],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 8],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 8],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 9],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 9],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 10],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 10],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 11],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 11],
            ["deskripsi" => "Berfungsi ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 12],
            ["deskripsi" => "Kondisi mika", "is_krusial" => 0, "mingguan_sub_kategori_id" => 12],
            ["deskripsi" => "Ketebalan ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 13],
            ["deskripsi" => "Kindisi chasing ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 13],
            ["deskripsi" => "Tekanan angin ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 13],
            ["deskripsi" => "Jumlah mur & baut roda lengkap", "is_krusial" => 0, "mingguan_sub_kategori_id" => 14],
            ["deskripsi" => "Kekencangan mur & baut roda", "is_krusial" => 0, "mingguan_sub_kategori_id" => 14],
            ["deskripsi" => "Ketebalan ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 15],
            ["deskripsi" => "Kindisi chasing ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 15],
            ["deskripsi" => "Tekanan angin ban", "is_krusial" => 0, "mingguan_sub_kategori_id" => 15],
            ["deskripsi" => "Jumlah mur & baut roda lengkap", "is_krusial" => 0, "mingguan_sub_kategori_id" => 16],
            ["deskripsi" => "Kekencangan mur & baut roda", "is_krusial" => 0, "mingguan_sub_kategori_id" => 16],
            ["deskripsi" => "Logo ‘P’ dan tulisan Pertamina", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Dilarang Menumpang", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Kapasitas kompartemen", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Ketinggian tangki", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Dilarang merokok", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "www.pertamina.com", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Awas kendaraan panjang & lebar", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Interlock, kotak alat, spill kit", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Batas kecepatan, no.telp.darurat/pengaduan", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Tanda pemeriksaan APAR", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Bahan bakar mudah terbakar", "is_krusial" => 0, "mingguan_sub_kategori_id" => 17],
            ["deskripsi" => "Oli mesin", "is_krusial" => 0, "mingguan_sub_kategori_id" => 18],
            ["deskripsi" => "Minyak rem", "is_krusial" => 0, "mingguan_sub_kategori_id" => 18],
            ["deskripsi" => "Minyak power steering", "is_krusial" => 0, "mingguan_sub_kategori_id" => 18],
            ["deskripsi" => "Ketinggian air dalam radiator & reservoar (cadangan)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 19],
            ["deskripsi" => "Daya lengket kipas (berat/ringan)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 19],
            ["deskripsi" => "Kebocoran air (pada mesin, selang radiator & waterpump)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 19],
            ["deskripsi" => "Tali kipas", "is_krusial" => 0, "mingguan_sub_kategori_id" => 19],
            ["deskripsi" => "Speling pedal kopling & rem", "is_krusial" => 0, "mingguan_sub_kategori_id" => 20],
            ["deskripsi" => "Minyak kopling", "is_krusial" => 0, "mingguan_sub_kategori_id" => 20],
            ["deskripsi" => "Speling kemudi (steer)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 20],
            ["deskripsi" => "Posisi kaca spion", "is_krusial" => 0, "mingguan_sub_kategori_id" => 20],
            ["deskripsi" => "Fungsi sabuk pengaman", "is_krusial" => 0, "mingguan_sub_kategori_id" => 20],
            ["deskripsi" => "Fungsi lampu indikator", "is_krusial" => 0, "mingguan_sub_kategori_id" => 21],
            ["deskripsi" => "Fungsi instrumen pendukung", "is_krusial" => 0, "mingguan_sub_kategori_id" => 21],
            ["deskripsi" => "Fungsi switch/saklar (lampu, klakson dll)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 21],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 22],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 23],
            ["deskripsi" => "Kebocoran tangki", "is_krusial" => 0, "mingguan_sub_kategori_id" => 24],
            ["deskripsi" => "Tutup tangki", "is_krusial" => 0, "mingguan_sub_kategori_id" => 24],
            ["deskripsi" => "Tutup accu", "is_krusial" => 0, "mingguan_sub_kategori_id" => 25],
            ["deskripsi" => "Kecukupan air accu", "is_krusial" => 0, "mingguan_sub_kategori_id" => 25],
            ["deskripsi" => "Kepala dan skun accu", "is_krusial" => 0, "mingguan_sub_kategori_id" => 25],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 26],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 27],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 28],
            ["deskripsi" => "Jumlah DCP (2pcs @ 9kg)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 29],
            ["deskripsi" => "Jumlah CO2 (1pcs @ 2kg)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 29],
            ["deskripsi" => "Tekanan indikator", "is_krusial" => 0, "mingguan_sub_kategori_id" => 29],
            ["deskripsi" => "Selang APAR", "is_krusial" => 0, "mingguan_sub_kategori_id" => 29],
            ["deskripsi" => "Masa berlaku APAR", "is_krusial" => 0, "mingguan_sub_kategori_id" => 29],
            ["deskripsi" => "Tidak terdapat sticker yang tidak standar", "is_krusial" => 0, "mingguan_sub_kategori_id" => 30],
            ["deskripsi" => "Kaca film tidak mengganggu pandangan", "is_krusial" => 0, "mingguan_sub_kategori_id" => 30],
            ["deskripsi" => "Kebocoran selang angin", "is_krusial" => 0, "mingguan_sub_kategori_id" => 31],
            ["deskripsi" => "Tombol emergency", "is_krusial" => 0, "mingguan_sub_kategori_id" => 31],
            ["deskripsi" => "Kebocoran seal & packing bottom loading", "is_krusial" => 1, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Hidrolic box ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Karet box", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Switch vapour & optic", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Switch pneumatic breaking", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Pengunci box", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Kondisi box", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Kebersihan box", "is_krusial" => 0, "mingguan_sub_kategori_id" => 32],
            ["deskripsi" => "Kecukupan oli pneumatic / airtech", "is_krusial" => 1, "mingguan_sub_kategori_id" => 33],
            ["deskripsi" => "Kebocoran seal", "is_krusial" => 1, "mingguan_sub_kategori_id" => 33],
            ["deskripsi" => "Indikator close & open", "is_krusial" => 0, "mingguan_sub_kategori_id" => 33],
            ["deskripsi" => "Hidrolic box ", "is_krusial" => 0, "mingguan_sub_kategori_id" => 33],
            ["deskripsi" => "Kepala selang", "is_krusial" => 0, "mingguan_sub_kategori_id" => 34],
            ["deskripsi" => "Tidak ada kebocoran", "is_krusial" => 0, "mingguan_sub_kategori_id" => 34],
            ["deskripsi" => "Jepitan kabel massa", "is_krusial" => 0, "mingguan_sub_kategori_id" => 35],
            ["deskripsi" => "Kabel (minimal 4 meter)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 35],
            ["deskripsi" => "API grafity (kepala babi)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Jumlah helmet", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Jas hujan", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Baji (ganjal roda)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Kotak P3K", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Dongkrak", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Kunci roda", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Traficone", "is_krusial" => 0, "mingguan_sub_kategori_id" => 36],
            ["deskripsi" => "Tidak ada pengikat dari segel bekal, kain dan tali (tidak standart)", "is_krusial" => 0, "mingguan_sub_kategori_id" => 37],
            ["deskripsi" => "Segel", "is_krusial" => 0, "mingguan_sub_kategori_id" => 38],
            ["deskripsi" => "Ketinggian T2", "is_krusial" => 0, "mingguan_sub_kategori_id" => 38],
            ["deskripsi" => "Kebocoran packing", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Fungsi engsel/pengunci", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Las titik", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Selang vapour valve", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Kabel sensor", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Bounding", "is_krusial" => 0, "mingguan_sub_kategori_id" => 39],
            ["deskripsi" => "Kondisi", "is_krusial" => 0, "mingguan_sub_kategori_id" => 40],
        ]);
        BulananPoin::insert([
            ["deskripsi" => "Tangga kabin, pegangan tangan", "bulanan_sub_kategori_id" => 1],
            ["deskripsi" => "Sabuk pengaman 3 point", "bulanan_sub_kategori_id" => 1],
            ["deskripsi" => "As Steering dan joint", "bulanan_sub_kategori_id" => 1],
            ["deskripsi" => "Fungsi pedal dan karet pedal", "bulanan_sub_kategori_id" => 1],
            ["deskripsi" => "Fungsi instrumen panel", "bulanan_sub_kategori_id" => 1],
            ["deskripsi" => "Saklar lampu & rotari", "bulanan_sub_kategori_id" => 2],
            ["deskripsi" => "Wiper dan karet wiper", "bulanan_sub_kategori_id" => 2],
            ["deskripsi" => "Klakson", "bulanan_sub_kategori_id" => 2],
            ["deskripsi" => "Alarm mundur", "bulanan_sub_kategori_id" => 2],
            ["deskripsi" => "Warna / Cat dan tanda-tanda", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Gril depan dan bumper", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Saklar utama", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Plat tutup mesin", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Tangki bahan bakar dan tutupnya", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Dudukan aki, kabel aki, dan tutupnya", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Spakbor dan penahan lumpur", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Fifth wheel, bushing dan pengunci", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Kekencangan baut roda", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Pelindung saringan knalpot", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Saluran dan dudukan pipa knalpot", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Seal rem di as roda depan", "bulanan_sub_kategori_id" => 3],
            ["deskripsi" => "Radiator dan sistem pendingin", "bulanan_sub_kategori_id" => 4],
            ["deskripsi" => "Water pump, V belt dan pulley", "bulanan_sub_kategori_id" => 4],
            ["deskripsi" => "Pompa injeksi", "bulanan_sub_kategori_id" => 5],
            ["deskripsi" => "Selang solar /filter", "bulanan_sub_kategori_id" => 5],
            ["deskripsi" => "Valve cover", "bulanan_sub_kategori_id" => 5],
            ["deskripsi" => "Kompresor", "bulanan_sub_kategori_id" => 5],
            ["deskripsi" => "Karter / Gasket & Plug", "bulanan_sub_kategori_id" => 6],
            ["deskripsi" => "Selang / pipa / tangki oli", "bulanan_sub_kategori_id" => 7],
            ["deskripsi" => "Pompa / steering box / as joint", "bulanan_sub_kategori_id" => 7],
            ["deskripsi" => "Draglink, drop arm, steering arm", "bulanan_sub_kategori_id" => 7],
            ["deskripsi" => "Blok mesin / gasket / dudukan", "bulanan_sub_kategori_id" => 7],
            ["deskripsi" => "Stater & altenator, dudukan dan kabel", "bulanan_sub_kategori_id" => 7],
            ["deskripsi" => "King pin as roda", "bulanan_sub_kategori_id" => 8],
            ["deskripsi" => "Velg / wheel rim", "bulanan_sub_kategori_id" => 8],
            ["deskripsi" => "Wheel bearing & Hub", "bulanan_sub_kategori_id" => 9],
            ["deskripsi" => "Leave spring / hanger / u-bolt / center bolt", "bulanan_sub_kategori_id" => 9],
            ["deskripsi" => "Shock breaker / bushing", "bulanan_sub_kategori_id" => 9],
            ["deskripsi" => "Dudukan dan Gear box", "bulanan_sub_kategori_id" => 9],
            ["deskripsi" => "Tongkat dan kabel transmisi", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "Dudukan transmisi", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "As kopel, baut dan joint", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "Center bearing / bearing gantung", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "Differensial", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "Kopling", "bulanan_sub_kategori_id" => 10],
            ["deskripsi" => "Balon udara / air bag", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Lengan dan bushing suspensi / Torque rod", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Lengan dan bushing stabilizer", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Shock breaker / bushing", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Wheel bearing & Hub", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Leave spring / hanger / u-bolt / center bolt", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Trunion", "bulanan_sub_kategori_id" => 11],
            ["deskripsi" => "Ketebalan kampas rem", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Selang rem", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Brake chamber, slack adjuster dan s-cam", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Spring brake actuator", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Brake drum", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Kabel / selang ABS", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Tangki udara", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "As roda belakang / gardan", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "Chassis, long / cross member", "bulanan_sub_kategori_id" => 12],
            ["deskripsi" => "King pin dan dudukan", "bulanan_sub_kategori_id" => 13],
            ["deskripsi" => "Selang udara dan kabel listrik", "bulanan_sub_kategori_id" => 13],
            ["deskripsi" => "Balon udara / air bag", "bulanan_sub_kategori_id" => 14],
            ["deskripsi" => "Lengan dan bushing suspensi / Torque rod", "bulanan_sub_kategori_id" => 14],
            ["deskripsi" => "Lengan dan bushing equalizer", "bulanan_sub_kategori_id" => 14],
            ["deskripsi" => "Shock breaker / bushing", "bulanan_sub_kategori_id" => 14],
            ["deskripsi" => "Leave spring / hanger / u-bolt / center bolt", "bulanan_sub_kategori_id" => 14],
            ["deskripsi" => "Ketebalan kampas rem", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Selang / pipa rem", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Wheel bearing & Hub", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Brake chamber, slack adjuster dan s-cam", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Kabel / selang ABS", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Tangki udara", "bulanan_sub_kategori_id" => 15],
            ["deskripsi" => "Kondisi cat & tanda-tanda", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Tangki, pipa, sambungan / flange outlet", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Rumah selang / hose tray", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Cam lock / selang discharge / seal / coupler", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Elbow, adaptor", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Interlock / katup darurat / katup penumatic", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Kontrol box / box", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Tangga kabin / hand rail", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Vapour vent / manhole dan selang & gasket", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Jarum terra", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Kabel ground", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "PTO", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Pompa discharge", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Flow meter", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Overfill sensor (semua kompartemen)", "bulanan_sub_kategori_id" => 16],
            ["deskripsi" => "Engine running test", "bulanan_sub_kategori_id" => 17],
        ]);
    }
}
